spring.cloud.bootstrap.enabled=true

spring.application.name=secretmanager
spring.datasource.url=jdbc:postgresql://localhost:5432/mydbssss
spring.datasource.username=${username}
spring.datasource.password=${password}

spring.antitamper.key=valorLocal

logging.level.org.springframework.cloud=DEBUG
logging.level.com.amazonaws=DEBUG